title: B-418
description: All models are wrong, but some are useful.

author: bean
avatar: /logo.png
email: imb2an@inha.edu
location: Incheon, Republic of Korea
skin: midnight
subscribe: False

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec
  - etc/

# Jekyll SEO Tag (Optional)
# =========================
# twitter:
#   username: ngzhio
#   card: summary
# logo: logo.jpg
# social:
#   name: Shangzhi Huang
#   links:
#     - https://twitter.com/ngzhio
#     - https://www.facebook.com/ngzhio
#     - https://github.com/ngzhio
# google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
